# Generated by Django 5.2.4 on 2026-07-21 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('shirt_number', models.PositiveSmallIntegerField(unique=True)),
                ('position', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('injured', 'Verletzt'), ('recovery', 'Aufbau'), ('absent', 'Abwesend')], default='available', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['shirt_number'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=160)),
                ('kickoff', models.DateTimeField()),
                ('competition', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('venue', models.CharField(choices=[('home', 'Heim'), ('away', 'Auswärts'), ('neutral', 'Neutral')], default='home', max_length=20)),
                ('goals_for', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals_against', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('mentality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('physicality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('performance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('potential', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.player')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Interner Teamreport', max_length=160)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('event_type', models.CharField(choices=[('training', 'Training'), ('match', 'Spiel'), ('recovery', 'Regeneration'), ('meeting', 'Besprechung'), ('other', 'Sonstiges')], default='training', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Teamtraining', max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('focus', models.CharField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=220)),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(130)])),
                ('mentality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('physicality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('performance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_performances', to='core.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_match_player')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Dabei'), ('cancelled', 'Abgesagt'), ('injured', 'Verletzt'), ('late', 'Verspätet')], default='present', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=220)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.trainingsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('training', 'player'), name='unique_training_player')],
            },
        ),
    ]
