from __future__ import annotations

from collections.abc import Mapping

BASE_UI = {
    "internal_board": "INTERNES TEAMBOARD",
    "dashboard": "Übersicht",
    "calendar": "Kalender",
    "training": "Training",
    "squad": "Kader",
    "matches": "Spiele",
    "reports": "Reports",
    "settings": "Team-Einstellungen",
    "next_event": "NÄCHSTER TERMIN",
    "private": "Intern & geschützt",
    "no_public_api": "Keine öffentliche API",
    "hello": "Guten Tag,",
    "internal_data": "Daten intern",
    "plan": "Planen",
    "logout": "Abmelden",
}

UI_TRANSLATIONS = {
    "en": {
        "internal_board": "INTERNAL TEAMBOARD",
        "dashboard": "Dashboard",
        "calendar": "Calendar",
        "training": "Training",
        "squad": "Squad",
        "matches": "Matches",
        "reports": "Reports",
        "settings": "Team settings",
        "next_event": "NEXT EVENT",
        "private": "Private & protected",
        "no_public_api": "No public API",
        "hello": "Hello,",
        "internal_data": "Internal data",
        "plan": "Plan",
        "logout": "Log out",
    },
    "ar": {
        "internal_board": "لوحة الفريق الداخلية",
        "dashboard": "لوحة التحكم",
        "calendar": "التقويم",
        "training": "التدريب",
        "squad": "الفريق",
        "matches": "المباريات",
        "reports": "التقارير",
        "settings": "إعدادات الفريق",
        "next_event": "الموعد القادم",
        "private": "خاص ومحمي",
        "no_public_api": "لا توجد واجهة عامة",
        "hello": "مرحباً،",
        "internal_data": "بيانات داخلية",
        "plan": "تخطيط",
        "logout": "تسجيل الخروج",
    },
    "fa": {
        "internal_board": "پنل داخلی تیم",
        "dashboard": "داشبورد",
        "calendar": "تقویم",
        "training": "تمرین",
        "squad": "بازیکنان",
        "matches": "بازی‌ها",
        "reports": "گزارش‌ها",
        "settings": "تنظیمات تیم",
        "next_event": "رویداد بعدی",
        "private": "خصوصی و محافظت‌شده",
        "no_public_api": "بدون API عمومی",
        "hello": "سلام،",
        "internal_data": "داده داخلی",
        "plan": "برنامه‌ریزی",
        "logout": "خروج",
    },
}

PHRASE_TRANSLATIONS = {
    "en": {
        "Team-Einstellungen": "Team settings",
        "Training, Kader und Leistung auf einen Blick.": "Training, squad and performance at a glance.",
        "Training planen": "Plan training",
        "Termin hinzufügen": "Add event",
        "AKTIVE SPIELER": "ACTIVE PLAYERS",
        "VERFÜGBAR": "AVAILABLE",
        "AUFBAU / VERLETZT": "RECOVERY / INJURED",
        "TEAMLEISTUNG": "TEAM PERFORMANCE",
        "KOMMENDE TAGE": "UPCOMING DAYS",
        "Team-Termine": "Team events",
        "Kalender öffnen": "Open calendar",
        "NÄCHSTER SCHRITT": "NEXT STEP",
        "Nächstes Training": "Next training",
        "Training vorbereiten": "Prepare training",
        "Jetzt planen": "Plan now",
        "Leistungsprofil": "Performance profile",
        "Klare Tendenz statt Datenflut.": "Clear trends instead of data overload.",
        "Bewertungen bleiben bewusst auf vier Kernwerte reduziert.": "Ratings stay focused on four core values.",
        "LETZTES SPIEL": "LAST MATCH",
        "Spielerleistungen": "Player performance",
        "Alle Spiele": "All matches",
        "SPIELER IM FOKUS": "PLAYER IN FOCUS",
        "Profil öffnen": "Open profile",
        "Schnell bewerten": "Quick rating",
        "Noch keine Termine geplant.": "No events planned yet.",
        "Noch keine Spielbewertungen.": "No match ratings yet.",
        "Noch nicht festgelegt": "Not set yet",
        "Ort offen": "Location pending",
        "Nationalität offen": "Nationality pending",
        "Spieler hinzufügen": "Add player",
        "Spieler speichern": "Save player",
        "Spieler wurde angelegt.": "Player created.",
        "Bewertung gespeichert.": "Rating saved.",
        "Training wurde geplant.": "Training planned.",
        "Termin wurde gespeichert.": "Event saved.",
        "Termin wurde aktualisiert.": "Event updated.",
        "Spiel wurde angelegt.": "Match created.",
        "Spielerleistung gespeichert.": "Player performance saved.",
        "Aufgabe zugewiesen.": "Task assigned.",
        "Report-Kommentar gespeichert.": "Report comment saved.",
        "Das Teamboard ist startklar.": "The teamboard is ready.",
        "Verfügbar": "Available",
        "Verletzt": "Injured",
        "Aufbau": "Recovery",
        "Abwesend": "Absent",
        "Dabei": "Present",
        "Abgesagt": "Cancelled",
        "Verspätet": "Late",
        "Geplant": "Planned",
        "Abgeschlossen": "Completed",
        "Regeneration": "Recovery",
        "Besprechung": "Meeting",
        "Sonstiges": "Other",
        "Heim": "Home",
        "Auswärts": "Away",
        "Neutral": "Neutral",
        "Übersicht": "Dashboard",
        "Kalender": "Calendar",
        "Kader": "Squad",
        "Spiele": "Matches",
        "Spieler": "Player",
        "Spiel": "Match",
        "Reports": "Reports",
        "Report": "Report",
        "Training": "Training",
        "Mentalität": "Mentality",
        "Physis": "Physicality",
        "Leistung": "Performance",
        "Potenzial": "Potential",
        "Kommentar": "Comment",
        "Datum": "Date",
        "Minuten": "Minutes",
        "Position": "Position",
        "Status": "Status",
        "Fokus": "Focus",
        "Einheit": "Session",
        "Ort": "Location",
        "Suchen": "Search",
        "Von": "From",
        "Bis": "To",
        "Filter löschen": "Clear filters",
        "Report erstellen": "Create report",
        "PDF / Drucken": "PDF / Print",
        "Erstellt am": "Created on",
        "Aktive Filter": "Active filters",
        "Alle Spieler": "All players",
        "Kommentar speichern": "Save comment",
        "Vertraulich – nur für den internen Gebrauch": "Confidential – internal use only",
        "Keine Weitergabe an Dritte": "Do not share with third parties",
        "Willkommen zurück": "Welcome back",
        "Melde dich mit deinem Trainer-Konto an.": "Sign in with your coach account.",
        "Benutzername": "Username",
        "Passwort": "Password",
        "Anmelden": "Sign in",
        "SICHERER ZUGANG": "SECURE ACCESS",
        "TEAM. DATEN. VERTRAUEN.": "TEAM. DATA. TRUST.",
        "Alles im Blick.": "Everything in view.",
        "Ohne Umwege.": "Without detours.",
        "Verschlüsselte Verbindung": "Encrypted connection",
        "Nur für autorisierte Trainer": "Authorized coaches only",
        "ERSTEINRICHTUNG": "FIRST-TIME SETUP",
        "Trainer-Zugang erstellen": "Create coach account",
        "Teamboard einrichten": "Set up teamboard",
        "Dieser Benutzer erhält Administrationsrechte.": "This user receives administrator rights.",
        "Vorname": "First name",
        "Nachname": "Last name",
        "Sicheres Passwort": "Secure password",
    },
    "ar": {
        "Team-Einstellungen": "إعدادات الفريق",
        "Training, Kader und Leistung auf einen Blick.": "التدريب والفريق والأداء في مكان واحد.",
        "Training planen": "تخطيط التدريب",
        "Termin hinzufügen": "إضافة موعد",
        "AKTIVE SPIELER": "اللاعبون النشطون",
        "VERFÜGBAR": "المتاحون",
        "AUFBAU / VERLETZT": "تأهيل / إصابة",
        "TEAMLEISTUNG": "أداء الفريق",
        "KOMMENDE TAGE": "الأيام القادمة",
        "Team-Termine": "مواعيد الفريق",
        "Kalender öffnen": "فتح التقويم",
        "NÄCHSTER SCHRITT": "الخطوة التالية",
        "Nächstes Training": "التدريب القادم",
        "Training vorbereiten": "تحضير التدريب",
        "Jetzt planen": "خطط الآن",
        "Leistungsprofil": "ملف الأداء",
        "Klare Tendenz statt Datenflut.": "اتجاه واضح دون إغراق بالبيانات.",
        "Bewertungen bleiben bewusst auf vier Kernwerte reduziert.": "تركز التقييمات على أربع قيم أساسية.",
        "LETZTES SPIEL": "آخر مباراة",
        "Spielerleistungen": "أداء اللاعبين",
        "Alle Spiele": "كل المباريات",
        "SPIELER IM FOKUS": "لاعب تحت المجهر",
        "Profil öffnen": "فتح الملف",
        "Schnell bewerten": "تقييم سريع",
        "Noch keine Termine geplant.": "لا توجد مواعيد مخططة بعد.",
        "Noch keine Spielbewertungen.": "لا توجد تقييمات مباريات بعد.",
        "Noch nicht festgelegt": "لم يحدد بعد",
        "Ort offen": "المكان غير محدد",
        "Nationalität offen": "الجنسية غير محددة",
        "Spieler hinzufügen": "إضافة لاعب",
        "Spieler speichern": "حفظ اللاعب",
        "Spieler wurde angelegt.": "تم إنشاء اللاعب.",
        "Training wurde geplant.": "تم تخطيط التدريب.",
        "Termin wurde gespeichert.": "تم حفظ الموعد.",
        "Termin wurde aktualisiert.": "تم تحديث الموعد.",
        "Spiel wurde angelegt.": "تم إنشاء المباراة.",
        "Spielerleistung gespeichert.": "تم حفظ أداء اللاعب.",
        "Aufgabe zugewiesen.": "تم تعيين المهمة.",
        "Report-Kommentar gespeichert.": "تم حفظ تعليق التقرير.",
        "Das Teamboard ist startklar.": "لوحة الفريق جاهزة.",
        "Verfügbar": "متاح",
        "Verletzt": "مصاب",
        "Aufbau": "تأهيل",
        "Abwesend": "غائب",
        "Dabei": "حاضر",
        "Abgesagt": "ملغي",
        "Verspätet": "متأخر",
        "Geplant": "مخطط",
        "Abgeschlossen": "مكتمل",
        "Regeneration": "استشفاء",
        "Besprechung": "اجتماع",
        "Sonstiges": "أخرى",
        "Heim": "على أرضنا",
        "Auswärts": "خارج الأرض",
        "Neutral": "محايد",
        "Übersicht": "لوحة التحكم",
        "Kalender": "التقويم",
        "Kader": "الفريق",
        "Spiele": "المباريات",
        "Spieler": "لاعب",
        "Spiel": "مباراة",
        "Reports": "التقارير",
        "Report": "تقرير",
        "Training": "التدريب",
        "Mentalität": "العقلية",
        "Physis": "الجاهزية البدنية",
        "Leistung": "الأداء",
        "Potenzial": "الإمكانات",
        "Kommentar": "ملاحظة",
        "Datum": "التاريخ",
        "Minuten": "الدقائق",
        "Position": "المركز",
        "Status": "الحالة",
        "Fokus": "التركيز",
        "Einheit": "الحصة",
        "Ort": "المكان",
        "Suchen": "بحث",
        "Von": "من",
        "Bis": "إلى",
        "Filter löschen": "مسح الفلاتر",
        "Report erstellen": "إنشاء التقرير",
        "PDF / Drucken": "PDF / طباعة",
        "Erstellt am": "أُنشئ في",
        "Aktive Filter": "الفلاتر النشطة",
        "Alle Spieler": "كل اللاعبين",
        "Kommentar speichern": "حفظ الملاحظة",
        "Vertraulich – nur für den internen Gebrauch": "سري – للاستخدام الداخلي فقط",
        "Keine Weitergabe an Dritte": "يمنع مشاركته مع أطراف خارجية",
        "Willkommen zurück": "مرحباً بعودتك",
        "Melde dich mit deinem Trainer-Konto an.": "سجّل الدخول بحساب المدرب.",
        "Benutzername": "اسم المستخدم",
        "Passwort": "كلمة المرور",
        "Anmelden": "تسجيل الدخول",
        "SICHERER ZUGANG": "دخول آمن",
        "TEAM. DATEN. VERTRAUEN.": "الفريق. البيانات. الثقة.",
        "Alles im Blick.": "كل شيء أمامك.",
        "Ohne Umwege.": "بوضوح وبساطة.",
        "Verschlüsselte Verbindung": "اتصال مشفر",
        "Nur für autorisierte Trainer": "للمدربين المصرح لهم فقط",
        "ERSTEINRICHTUNG": "الإعداد الأول",
        "Trainer-Zugang erstellen": "إنشاء حساب المدرب",
        "Teamboard einrichten": "إعداد لوحة الفريق",
        "Dieser Benutzer erhält Administrationsrechte.": "سيحصل هذا المستخدم على صلاحيات الإدارة.",
        "Vorname": "الاسم الأول",
        "Nachname": "اسم العائلة",
        "Sicheres Passwort": "كلمة مرور آمنة",
    },
    "fa": {
        "Team-Einstellungen": "تنظیمات تیم",
        "Training, Kader und Leistung auf einen Blick.": "تمرین، بازیکنان و عملکرد در یک نگاه.",
        "Training planen": "برنامه‌ریزی تمرین",
        "Termin hinzufügen": "افزودن رویداد",
        "AKTIVE SPIELER": "بازیکنان فعال",
        "VERFÜGBAR": "در دسترس",
        "AUFBAU / VERLETZT": "ریکاوری / مصدوم",
        "TEAMLEISTUNG": "عملکرد تیم",
        "KOMMENDE TAGE": "روزهای آینده",
        "Team-Termine": "رویدادهای تیم",
        "Kalender öffnen": "باز کردن تقویم",
        "NÄCHSTER SCHRITT": "گام بعدی",
        "Nächstes Training": "تمرین بعدی",
        "Training vorbereiten": "آماده‌سازی تمرین",
        "Jetzt planen": "الان برنامه‌ریزی کن",
        "Leistungsprofil": "پروفایل عملکرد",
        "LETZTES SPIEL": "آخرین بازی",
        "Spielerleistungen": "عملکرد بازیکنان",
        "Alle Spiele": "همه بازی‌ها",
        "SPIELER IM FOKUS": "بازیکن منتخب",
        "Profil öffnen": "مشاهده پروفایل",
        "Schnell bewerten": "ارزیابی سریع",
        "Verfügbar": "در دسترس",
        "Verletzt": "مصدوم",
        "Aufbau": "ریکاوری",
        "Abwesend": "غایب",
        "Dabei": "حاضر",
        "Abgesagt": "لغو شده",
        "Verspätet": "با تأخیر",
        "Geplant": "برنامه‌ریزی‌شده",
        "Abgeschlossen": "تکمیل‌شده",
        "Übersicht": "داشبورد",
        "Kalender": "تقویم",
        "Kader": "بازیکنان",
        "Spiele": "بازی‌ها",
        "Spieler": "بازیکن",
        "Spiel": "بازی",
        "Reports": "گزارش‌ها",
        "Report": "گزارش",
        "Training": "تمرین",
        "Mentalität": "ذهنیت",
        "Physis": "آمادگی جسمانی",
        "Leistung": "عملکرد",
        "Potenzial": "پتانسیل",
        "Kommentar": "یادداشت",
        "Datum": "تاریخ",
        "Minuten": "دقیقه",
        "Position": "پست",
        "Status": "وضعیت",
        "Fokus": "تمرکز",
        "Ort": "مکان",
        "Suchen": "جستجو",
        "Von": "از",
        "Bis": "تا",
        "Filter löschen": "پاک کردن فیلترها",
        "Report erstellen": "ساخت گزارش",
        "PDF / Drucken": "PDF / چاپ",
        "Willkommen zurück": "خوش آمدید",
        "Benutzername": "نام کاربری",
        "Passwort": "رمز عبور",
        "Anmelden": "ورود",
        "Vorname": "نام",
        "Nachname": "نام خانوادگی",
        "Sicheres Passwort": "رمز عبور امن",
    },
}

RTL_LANGUAGES = {"ar", "fa", "he", "ur"}


def language_prefix(language_code: str) -> str:
    return (language_code or "de").split("-")[0].lower()


def get_ui(language_code: str, custom: Mapping[str, str] | None = None) -> dict[str, str]:
    language = language_prefix(language_code)
    result = dict(BASE_UI)
    result.update(UI_TRANSLATIONS.get(language, {}))
    if custom:
        for key, value in custom.items():
            if key in result and isinstance(value, str):
                result[key] = value
    return result


def translate_content(content: str, language_code: str, custom: Mapping[str, str] | None = None) -> str:
    language = language_prefix(language_code)
    translations = dict(PHRASE_TRANSLATIONS.get(language, {}))
    if custom:
        translations.update({str(key): str(value) for key, value in custom.items()})
    if not translations:
        return content
    for source in sorted(translations, key=len, reverse=True):
        content = content.replace(source, translations[source])
    return content
